image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:stable

stages:
  - build test
  - push
  # - deploy

variables:
  # DOCKER_HOST: tcp://gitlab-runner.home.lan:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:dind

build test:
  stage: build test
  before_script:
    - docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
  script:
    - docker build -t docker-ansible .
    - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible
    - docker exec --tty test-container env TERM=xterm ansible --version
  after_script:
    - docker stop test-container
    - docker rm test-container

push:
  needs: ["build test"]
  stage: push
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  after_script:
    - docker rmi "$CI_REGISTRY_IMAGE"